server:
  port: 8761
spring:
  application:
    name: demo-server
security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
---
spring:
  #指定profiles = peer1
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    #指定当profiles = peer1时 主机名是peer1
    hostname: peer1
  client:
    serviceUrl:
      #registerWithEureka: false
      #fetchRegistry: false
      defaultZone: http://user:123456@peer2:8762/eureka
---
spring:
 #指定profiles = peer2
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
   #指定当profiles = peer2时 主机名是peer2
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://user:123456@peer1:8761/eureka




###################################################
#
# 启动profiles = peer1
# java -jar demo-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
#
###################################################
#
# 启动profiles = peer2
# java -jar demo-server-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
#
###################################################
#
# peer1注册中心地址 http://peer1:8761
# peer2注册中心地址 http://peer2:8762
#
###################################################
#
#
#
###################################################