server:
  port: 8761
spring:
  application:
    name: demo-server
eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: false
      defaultZone: http://localhost:8761/eureka
